# CMake generated Testfile for 
# Source directory: /home/chen/work/bluez/install/libical/src/test
# Build directory: /home/chen/work/bluez/install/libical/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(regression "/home/chen/work/bluez/install/libical/src/test/regression")
set_tests_properties(regression PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;100;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-0 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/0.ics")
set_tests_properties(parser-0 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-1-1 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/1-1.ics")
set_tests_properties(parser-1-1 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-1 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/1.ics")
set_tests_properties(parser-1 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-2 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/2.ics")
set_tests_properties(parser-2 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-2445 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/2445.ics")
set_tests_properties(parser-2445 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-2446 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/2446.ics")
set_tests_properties(parser-2446 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-3 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/3.ics")
set_tests_properties(parser-3 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-4 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/4.ics")
set_tests_properties(parser-4 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-5 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/5.ics")
set_tests_properties(parser-5 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-6 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/6.ics")
set_tests_properties(parser-6 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-7 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/7.ics")
set_tests_properties(parser-7 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-8 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/8.ics")
set_tests_properties(parser-8 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-calendar "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/calendar.ics")
set_tests_properties(parser-calendar PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-caltime "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/caltime.ics")
set_tests_properties(parser-caltime PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-classify "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/classify.ics")
set_tests_properties(parser-classify PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-crash "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/crash.ics")
set_tests_properties(parser-crash PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-get_char_test "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/get_char_test.ics")
set_tests_properties(parser-get_char_test PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-incoming "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/incoming.ics")
set_tests_properties(parser-incoming PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-issue250 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/issue250.ics")
set_tests_properties(parser-issue250 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-issue251 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/issue251.ics")
set_tests_properties(parser-issue251 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-issue252 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/issue252.ics")
set_tests_properties(parser-issue252 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-issue253 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/issue253.ics")
set_tests_properties(parser-issue253 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-issue339 "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/issue339.ics")
set_tests_properties(parser-issue339 PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-large "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/large.ics")
set_tests_properties(parser-large PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-malloc "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/malloc.ics")
set_tests_properties(parser-malloc PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-overlaps "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/overlaps.ics")
set_tests_properties(parser-overlaps PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-process-calendar "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/process-calendar.ics")
set_tests_properties(parser-process-calendar PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-process-incoming "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/process-incoming.ics")
set_tests_properties(parser-process-incoming PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-recur-errors "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/recur-errors.ics")
set_tests_properties(parser-recur-errors PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-restriction "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/restriction.ics")
set_tests_properties(parser-restriction PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-smallcluster "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/smallcluster.ics")
set_tests_properties(parser-smallcluster PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-spanlist "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/spanlist.ics")
set_tests_properties(parser-spanlist PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-stresstest "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/stresstest.ics")
set_tests_properties(parser-stresstest PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(parser-zday "/home/chen/work/bluez/install/libical/src/test/parser" "/home/chen/work/bluez/install/libical/test-data/zday.ics")
set_tests_properties(parser-zday PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;110;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(recur "/home/chen/work/bluez/install/libical/src/test/recur")
set_tests_properties(recur PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;125;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(icaltm_test "/home/chen/work/bluez/install/libical/src/test/icaltm_test")
set_tests_properties(icaltm_test PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;137;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(testmime "/home/chen/work/bluez/install/libical/src/test/testmime")
set_tests_properties(testmime PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;144;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(testvcal "/home/chen/work/bluez/install/libical/src/test/testvcal")
set_tests_properties(testvcal PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;150;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(process "/home/chen/work/bluez/install/libical/src/test/process")
set_tests_properties(process PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;155;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(timezones "/home/chen/work/bluez/install/libical/src/test/timezones")
set_tests_properties(timezones PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;161;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
add_test(builtin_timezones "/home/chen/work/bluez/install/libical/src/test/builtin_timezones")
set_tests_properties(builtin_timezones PROPERTIES  WORKING_DIRECTORY "/home/chen/work/bluez/install/libical/bin" _BACKTRACE_TRIPLES "/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;77;add_test;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;167;testme;/home/chen/work/bluez/install/libical/src/test/CMakeLists.txt;0;")
